Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "AllowMouseOpenFail" "true"
    Option "DontVTSwitch" "true"
EndSection

Section "Device"
    Identifier "DummyVideoCard"
    Driver "dummy"
    VideoRam 256000
EndSection

Section "Monitor"
    Identifier "DummyMonitor"
    HorizSync 5.0-1000.0
    VertRefresh 5.0-200.0
    Modeline "1364x1024_60.00" 115.91 1364 1456 1600 1836 1024 1025 1028 1052 -HSync +VSync
EndSection

Section "Screen"
    Identifier "DummyScreen"
    Device "DummyVideoCard"
    Monitor "DummyMonitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1364x1024_60.00"
        Virtual 1364 1364
    EndSubSection
EndSection
